### ISSUE TITLE
Plan for May 2020

### ISSUE THREAD

**Issue by antonvolkoff** [antonvolkoff/kosmos#13]
General
---
- [x] Open source Kosmos
- [x] Better performance with a big number of elements on a canvas
- [ ] Load Clojure files into Kosmos (Experiment)
- [ ] Undo/redo manipulations https://github.com/antonvolkoff/kosmos/issues/6
- [ ] File format (Experiment)
- [ ] Good enough drawing experience 

UX/UI
----
- [x] Adjust the distance between atoms when typing https://github.com/antonvolkoff/kosmos/issues/10
- [x] Switch between ready, enter, edit and connect modes
- [x] Show hide transcript panel https://github.com/antonvolkoff/kosmos/issues/4
- [ ] File/namespace navigation #18 
- [ ] Create coding layers
- [ ] Copy/Cut/Paste atoms https://github.com/antonvolkoff/kosmos/issues/7
- [ ] Disconnect atoms
- [ ] Copy/paste text inside atoms
- [ ] Multiple atoms select

iPad
----
- [ ] Create a prototype of an iPad application
